'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Eye, Download } from 'lucide-react';

// TODO: Replace with actual data fetching
const MOCK_TOURS = [
  {
    id: 'tour-001',
    customerName: 'John Doe',
    destination: 'Paris, France',
    startDate: '2024-04-15',
    endDate: '2024-04-22',
    status: 'pending',
    agent: 'Alice Johnson',
    createdAt: '2024-03-01',
  },
  {
    id: 'tour-002',
    customerName: 'Jane Smith',
    destination: 'Tokyo, Japan',
    startDate: '2024-05-01',
    endDate: '2024-05-08',
    status: 'confirmed',
    agent: 'Bob Wilson',
    createdAt: '2024-03-02',
  },
  {
    id: 'tour-003',
    customerName: 'Mike Brown',
    destination: 'New York, USA',
    startDate: '2024-06-10',
    endDate: '2024-06-17',
    status: 'cancelled',
    agent: 'Charlie Davis',
    createdAt: '2024-03-03',
  },
];

export default function ToursPage() {
  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'pending':
        return <Badge variant="secondary" className="bg-yellow-100 text-yellow-800">Pending</Badge>;
      case 'confirmed':
        return <Badge variant="secondary" className="bg-green-100 text-green-800">Confirmed</Badge>;
      case 'cancelled':
        return <Badge variant="destructive">Cancelled</Badge>;
      default:
        return <Badge variant="outline">Unknown</Badge>;
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Tours</h1>
        <p className="text-muted-foreground">Manage all tour leads and bookings</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Tour Leads</CardTitle>
          <CardDescription>View and manage all tour leads generated by agents</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Customer</TableHead>
                <TableHead>Destination</TableHead>
                <TableHead>Dates</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Agent</TableHead>
                <TableHead>Created</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {MOCK_TOURS.map((tour) => (
                <TableRow key={tour.id}>
                  <TableCell className="font-medium">{tour.customerName}</TableCell>
                  <TableCell>{tour.destination}</TableCell>
                  <TableCell>
                    {tour.startDate} - {tour.endDate}
                  </TableCell>
                  <TableCell>{getStatusBadge(tour.status)}</TableCell>
                  <TableCell>{tour.agent}</TableCell>
                  <TableCell>{tour.createdAt}</TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      <Button variant="ghost" size="icon" title="View Details">
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button variant="ghost" size="icon" title="Download Documents">
                        <Download className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
} 